### ISSUE TITLE
ASSERT: "copy" in file thread/qmutex.cpp, line 595 The program has unexpectedly finished.

### ISSUE THREAD

**Issue by GerrieWell** [artivis/MOSSE_tracker#1]
This project can't run successfully. I try a few avi videos. all return this error just as I click load video file: 

```
ASSERT: "copy" in file thread/qmutex.cpp, line 595
The program has unexpectedly finished.
```

**Comment by GerrieWell** [comment]
And there aren't any other oops information. I can't locate which line occur error .

**Comment by artivis** [comment]
Hi,  
as I remember this was working with a webcam stream.  
Please notice that this is an old school project posted as is and that I am not really willing to maintain/debug.  
Please feel free to propose a pull request is you fix any encountered issue.
